import { Inter } from "next/font/google";
import "../../styles/global.css";
import GlassPane from "@/components/GlassPane";
import clsx from "clsx";

export const metadata = {
  title: "FullStack app Home",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function AuthRootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body
        className={clsx("h-screen w-screen rainbow-mesh p-6", inter.className)}
      >
        <GlassPane className="w-full h-full flex items-center justify-center">
          {children}
        </GlassPane>
      </body>
    </html>
  );
}
