import "@/styles/global.css";
import GlassPane from "@/components/GlassPane";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import clsx from "clsx";

export const metadata = {
  title: "FullStack app Home",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function DashboardRootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body
        className={clsx("h-screen w-screen candy-mesh p-6", inter.className)}
      >
        <GlassPane className="w-full h-full p-6 flex align-center container mx-auto">
          <Sidebar />
          <main className="w-full pl-6 h-full">{children}</main>
        </GlassPane>
        <div id="modal"></div>
      </body>
    </html>
  );
}
